# Generated by Django 2.2.12 on 2021-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=225)),
                ('title', models.CharField(default='', max_length=225)),
                ('description', models.CharField(default='', max_length=225)),
                ('url', models.SlugField()),
                ('urlToImage', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('publishedAt', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
