# Generated by Django 2.2.12 on 2021-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporterKidiary', '0002_auto_20210501_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('economy', 'ECONOMY'), ('basicnews', 'BASICNEWS'), ('health', 'HEALTH'), ('national', 'NATIONAL'), ('international', 'INTERNATIONAL'), ('sports', 'SPORTS')], default='basicnews', max_length=15),
        ),
    ]
