# Generated by Django 2.2.12 on 2021-05-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporterKidiary', '0003_newspost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('economy', 'ECONOMY'), ('basicnews', 'BASICNEWS'), ('health', 'HEALTH'), ('national', 'NATIONAL'), ('international', 'INTERNATIONAL'), ('sports', 'SPORTS'), ('technology', 'TECHNOLOGY')], default='basicnews', max_length=15),
        ),
    ]
